import type { Metadata } from "next";
import { Geist_Mono, Poppins } from "next/font/google";
import "./globals.css";

import Footer from "@/components/Footer";
import { Providers } from "./provider";
import NavBar from "@/components/HeroNavBar";

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const poppins = Poppins({
  subsets: ['latin'],
  weight: ['400', '700'],
  variable: '--font-poppins',
});

export default function RootLayout({children,}: {children: React.ReactNode;}) {
  return (
    <html lang="en" className="scroll-smooth">
      <body className={`${poppins.variable} ${geistMono.variable} antialiased`}>
        <Providers>
          <NavBar />
            {children}
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
